### PR TITLE
Commented the imu line out.

### PR DESCRIPTION
**Pull request by nickvaras**
This topic mapping should be revised, the node originally looks for /imu/data , so the way this is remapped might not be doing anything. If it is doing something, i.e., if it succeeds into remapping to vector/feedback/sic_imu , then it might be doing more harm than good, as that topic does not currently contain orientation data... (Not sure if it matters or not). Either way, seems to be redundant.

### CODE REVIEW

**Comment by PatrickHussey** [comment]
This should not be changed since the new xsense IMU provides an orientation estimate. Will leave it open until that happens.

There needs to be a determination on which IMU the embedded system has since there are a number of platforms out there with the v1 ST IMU that does not provide a embedded orientation estimate and require the madwick filter or some other type of estimation filter

**Comment by nickvaras** [comment]
Apologies for not explaining myself correctly, my intention is not to
disable the IMU as an input, but to correct what I believe to be an error
in the topic name for the mentioned input.
According to  http://wiki.ros.org/laser_scan_matcher , the IMU input comes
in through the "imu/data" topic by default, but in the launch file we remap
the "/imu" topic instead. Because we have a topic named "imu/data" being
published, LSM is taking it as its input (when the intention is for it to
take "/vector/feedback/sic_imu". Because /imu/data and
/vector/feedback/sic_imu seem to publish almost identical data, the bug is
unnoticable, but for the sake of rigurosity, we should either:

-Eliminate (or comment out at least) the IMU topic remapping or,

-change <remap from="/imu" to="/vector/feedback/sic_imu"/>    to     <remap
from="/imu/data" to="/vector/feedback/sic_imu"/>

**Comment by PatrickHussey** [comment]
I understand the issue, you are trying to immediately solve

My point is that when we permanently switch to the MTi-2 you'll need:

<remap from="/imu/data" to="/vector/feedback/sic_imu"/>

because the Mti-2 provides an orientation estimate. Or have vector_data_classes.py publish the full xsense orientation estimate on /imu/data based on the bit in the serial number that tells you which IMU the system has

for all existing machines with the old 9-axis chip on the SIC the line can just be commented out since we use the madgwick filter in ROS to generate the orientation estimate from raw acceleration

But we will need to do more than just comment it out for the new IMU was the point

**Comment by nickvaras** [comment]
Ok.

**Pull request closed without merging**
